### ISSUE TITLE
Issues about xenko/build/LaunchWindowsSolution.bat

### ISSUE THREAD

**Issue by leaverChina** [SiliconStudio/xenko#347]
Why init the path "C:\Program Files\Microsoft Visual Studio 14.0\Common7\IDE\devenv"? I install in "E:\Program Files\Microsoft Visual Studio 14.0\Common7\IDE\devenv",

and what different between double click LaunchWindowsSolution.bat and Xenko.sln?

**Comment by xenux** [comment]
Hi,
I just fix the problem on our internal repo. 
It should be replicated soon on the public branch.

The LaunchxxxxSolution.bat scripts set the SiliconStudioXenkoDir to the current dev folder before launching VS. This is needed for proper compilation and execution of the projects in the solution. If you have only one dev folder you probably don't need to use it. We use it internally because we usual work with several checkouts of the project in different states in parallel (different branches).

**Comment by Benlitz** [comment]
Just for the record, LaunchWindowsSolution.bat is not needed anymore. Need to check for the Android/iOS ones but if it's ok we will remove these files to avoid confusion.
