### ISSUE TITLE
Xenko 1.6.6 crashes on any Android device

### ISSUE THREAD

**Issue by jaladaGmbH** [SiliconStudio/xenko#408]
Create new SpaceEscape example project. Open Visual Studio 2015. Select any Android device or emulator for debugging and you get the attached crash (debug) report. 

[Debug.zip](https://github.com/SiliconStudio/xenko/files/287049/Debug.zip)

Best regards

**Comment by sinkingsugar** [comment]
Please try to update to the latest Xamarin (probably alpha release even, try stable first maybe anyway) I think your Xamarin version is the issue.

**Comment by jaladaGmbH** [comment]
I have the latest stable version of Xamarin installed. Do you think it is a good idea to make a release for Android based on an untested alpha release?

**Comment by jaladaGmbH** [comment]
I have tested our game with the latest beta version of Xamarin, I can start the app now on the Android device without any error. But if I would like to debug the app, I get now the following exception "libaot-System.Runtime.Serialization.dll.so not found"

Any Idea? I know it's now a Xamarin problem but it would be nice to have a solution.

Best regards
jaladaGmbH

**Comment by xen2** [comment]
Unfortunately the stable => alpha switch was necessary for us due to some issues on Xamarin-side, which is beyond our control.

The libaot exception is unrelated and not a problem (it is more information to explain AOT data was not found, but it still works fine with JIT).
There is probably something else in the log a little bit further?

**Comment by xen2** [comment]
Closing since main issue is resolved, please reopen another issue if you have other problems.
