### ISSUE TITLE
New particles do not render in scene until you close/open scene

### ISSUE THREAD

**Issue by dfkeenan** [SiliconStudio/xenko#422]
Basically just have to add a new entity with a particle component. You can't see anything in game studio but works when game is run.

**Comment by LautrecOfCarim** [comment]
Thanks for the report, I confirmed the issue and should fix it soon. When you have an already existing entity and you add a ParticleSystem component to it it doesn't render until the whole scene is reloaded. If you add the entity to the scene (with the component already in it) it works fine, which is why the game works since it uses ready data.

**Comment by LautrecOfCarim** [comment]
The issue was related to a problem where a component added to an existing entity didn't have its properties updated, we fixed it internally and should be out in 1.7.1.

**Comment by dfkeenan** [comment]
Nice work.
