### ISSUE TITLE
SDF font Segoe UI wrong render

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#436]
Hi, looks like SDF font Segoe UI Bold, Italic has problem with some of the characters. Characters a,d,g,q and K are wrong. I tried few more fonts and didn't find any other with the same issue so it could be font related.

**Comment by LautrecOfCarim** [comment]
Hi, thanks for the report, I'll look into it.

**Comment by LautrecOfCarim** [comment]
It seems it was a problem with the msdfgen.exe tool we are using and it turned out there is such an issue on the original branch. Basically some fancier font glyphs didn't load properly and failed to output an image. There was a fix on the original repo which works for me so I'm attaching the patched tool (zip password is msdfgen). You can extract it and replace msdfgen.exe which Xenko is using (or just wait for the next update).

[msdfgen.zip](https://github.com/SiliconStudio/xenko/files/373233/msdfgen.zip)

**Comment by EmptyKeys** [comment]
thanks :)

**Comment by EmptyKeys** [comment]
working fine in 1.7.6-beta ... closing
