### ISSUE TITLE
BuildCache in Local Temp for old version

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#509]
I think that installer should remove Build Cache for old version when installing new. I found out that I had like 10GB of data in that directory, which were for older versions.

**Comment by Benlitz** [comment]
We'll provide a way to manage and clean the build cache at some point, as you say it can grow very big. Cleaning it on install it not ideal, because one might want to use multiple versions of Xenko on the same machine.
We are currently improving our build engine so the way we are caching things might change, but we'll try to provide something for the official release.

**Comment by EmptyKeys** [comment]
I understand that you can use more version than one, but if you **deleting** old version by your tool, it should **delete everything**, including Build Cache. 
I don't think this is suggestion. It's actually bug in your installer.

**Comment by Benlitz** [comment]
yes I agree on this
