### ISSUE TITLE
Exception in Resource Binder

### ISSUE THREAD

**Issue by EmptyKeys** [SiliconStudio/xenko#574]
Hi,
upgrading my code to version 2.0 and I got issue with rendering vertex buffers. Old (1.10) code is raising this exception:

Unable to cast object of type 'SiliconStudio.Xenko.Graphics.Buffer' to type 'SiliconStudio.Xenko.Graphics.SamplerState'.

   at SiliconStudio.Xenko.Graphics.ResourceBinder.BindResources(CommandList commandList, DescriptorSet[] descriptorSets)
   at SiliconStudio.Xenko.Rendering.EffectInstance.Apply(GraphicsContext graphicsContext)
   at EmptyKeys.UserInterface.Renderers.XenkoRenderer.DrawGeometry(GeometryBuffer buffer, PointF position, Single depth) in E:\!Prog\TFS\LogicMarbles\UIGenerator\EmptyKeys.UserInterface.Paradox\Renderers\XenkoRenderer.cs:line 491

So I propably not doing something correct for version 2.0. 

My buffer implementation is here, FillColor method - https://github.com/EmptyKeys/UI_Engines/blob/master/EmptyKeys.UserInterface.Xenko/Media/XenkoGeometryBuffer.cs

Draw Geometry is here - https://github.com/EmptyKeys/UI_Engines/blob/master/EmptyKeys.UserInterface.Xenko/Renderers/XenkoRenderer.cs

**Comment by jwollen** [comment]
Thanks for the report.
Would you mind creating a small reproduction project? (only binaries, no need for the EmptyKeys source)
Thanks!

**Comment by EmptyKeys** [comment]
There you go - http://emptykeys.com/uploads/xenko2issue.zip

Binaries in Bin/Windows/Debug

**Comment by jwollen** [comment]
Thanks!
In `XenkoRenderer.DrawGeometry`, could you try to call `xenkoBuffer.EffectInstance.Apply(...)` after `graphicsContext.CommandList.SetPipelineState(...)`?

`EffectInstance.Apply` will call `CommandList.SetDescriptorSets`, which works with the currently set pipeline.
I think we were doing this lazily before, so the order didn't matter, but we are enforcing it since 2.0.

Let me know if that works!

**Comment by EmptyKeys** [comment]
Yup, that did it! Time to upgrade to 2.0 :)
